### ISSUE TITLE
questions from stackoverflow not displaying

### ISSUE THREAD

**Issue by SandeepBiradar** [Charcoal-SE/Blaze#29]
After selecting fetch questions on  http://erwaysoftware.com/blaze/# , Questions are not displayed it is giving error as  "Uncaught ReferenceError: isLoggedIn is not defined" as shown in the image below.

![Error](http://i.stack.imgur.com/ga1OI.jpg)

Browser:  Google chrome Version 51.0.2704.79 m

**Comment by ArtOfCode-** [comment]
@SandeepBiradar Questions haven't had much attention at all, really. I've committed something *should* fix this, but there may well be other unfixed bugs in the questions view.

Waiting on @Undo1 to deploy this.

**Comment by Undo1** [comment]
Deployed; looks like 52d0944 from Art fixed this.
