### ISSUE TITLE
Links to comments are not obvious

### ISSUE THREAD

**Issue by flux77** [Charcoal-SE/blaze#40]
Suppose I fetched all comments for a site. In the list of comments, the link to the comment is on the timestamp. This is not obvious. Could you make the link more obvious? It is not obvious that the link to the actual comment is on the timestamp!

Every time I use Blaze after a long break, I fumble around the web interface because I forget where the link is.

https://github.com/Charcoal-SE/blaze/blob/1fa8567f0e5e1494dc531934367c603e0f52bd4e/script.js#L461-L466

**Comment by Undo1** [comment]
You have no idea how much it warms my heart to see people still using a project written, in complete naivety, more than seven years ago at a... far more tender age.

Ask you you shall receive.

<img width="678" alt="Screen Shot 2021-05-22 at 8 43 45 PM" src="https://user-images.githubusercontent.com/5162342/119246423-b12fd300-bb3e-11eb-84dc-adb493445717.png">
